# docker-compose -f docker-compose-test.yaml up --build
# docker-compose -f docker-compose-test.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../
      dockerfile: ./workflow-calcium-imaging/Dockerfile.test
    image: workflow_calcium_imaging:0.1.0a2
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - IMAGING_ROOT_DATA_DIR=/main/test_data
      - DATABASE_PREFIX=test_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest -sv --cov-report term-missing --cov=workflow_calcium_imaging -p no:warnings
        tail -f /dev/null
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
    depends_on:
      db:
        condition: service_healthy
networks:
  main: