# MYSQL_VER=8.0 docker compose up -f docker-compose-db.yaml --build
version: "2.4"
services:
  db:
    mem_limit: 12g
    restart: always
    image: datajoint/mysql:${MYSQL_VER}
    environment:
      - MYSQL_ROOT_PASSWORD=${DJ_PASS}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 15s
      retries: 10
      interval: 15s