# docker-compose -f ./docker/docker-compose-dev.yaml up --build -d
# docker-compose -f ./docker/docker-compose-dev.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow-calcium-imagin-dev:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-calcium-imaging/docker/Dockerfile.dev
    env_file: .env
    image: workflow_calcium_imaging_dev:0.1.0a2
    environment:
      - IMAGING_ROOT_DATA_DIR=/main/test_data/workflow_calcium_imaging/
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-calcium-imaging:/main/element-calcium-imaging
      - ..:/main/workflow-calcium-imaging
    depends_on:
      db:
        condition: service_healthy
networks:
  main: