version: "3"
services:
  app:
    extends:
      file: ./local/docker-compose.yaml
      service: app
    image: datajoint/workflow_calcium_imaging_devcontainer:latest
    environment:
      - DJ_PUBLIC_S3_LOCATION=djhub.vathes.datapub.elements:/workflow-calcium-imaging-data-v2
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
volumes:
  docker_data: