name: Test
on:
  push:
  pull_request:
jobs:
  devcontainer-build:
    uses: datajoint/dj-gha-workflows/.github/workflows/devcontainer-build.yaml@main
    secrets:
      DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      dockerhub_token: ${{secrets.dockerhub_token}}

